name              = "my-sveltekit-worker"
main              = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-06-10"
assets            = { binding = "ASSETS", directory = ".svelte-kit/cloudflare" }
